### ISSUE TITLE
Enhancement:  handle routing from 'leaf devices'

### ISSUE THREAD

**Issue by stevebus** [sandervandevelde/EdgeRouteFlow#1]
This is not a 'bug', but an enhancement request...  :-)

First of all, outstanding work!  this is very cool.   One nice feature to have would be handling the case of routing messages from downstream or 'leaf' devices..   An example is below..

The "routetoformatterFromLeaf" route takes any data that comes from a downstream or leaf device and routes it to the formatter module.  This part doesn't get visualized and it appears that all data originates in the formatter module, which isn't right.   Would be a nice feature to have.

{
  "routes": {
    "routeFormattterToASA": "FROM /messages/modules/formattermodule/outputs/* INTO BrokeredEndpoint(\"/modules/aggrASAJob/inputs/inputFromHub\")",
    "routetolog": "FROM /messages/* INTO BrokeredEndpoint(\"/modules/logmodule/inputs/input1\")",
    "routetoformatterFromLeaf": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/formattermodule/inputs/input1\")",
    "routeASAToIoTHub": "FROM /messages/modules/aggrASAJob/outputs/outputToHub  INTO $upstream"
  }
}

**Comment by sandervandevelde** [comment]
I updated the regex to handle:

> {
"routes": {
"routeFormattterToASA": "FROM /messages/modules/formattermodule/outputs/* INTO BrokeredEndpoint(\"/modules/aggrASAJob/inputs/inputFromHub\")",
"routetolog": "FROM /messages/* INTO BrokeredEndpoint(\"/modules/logmodule/inputs/input1\")",
"routetoformatterFromLeaf": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/formattermodule/inputs/input1\")",
"routeASAToIoTHub": "FROM /messages/modules/aggrASAJob/outputs/outputToHub INTO $upstream"
}
}

Please note the escaped double-quotes.

Is this what you need?

**Comment by stevebus** [comment]
not exactly..  I see that it adds an "all modules" block on the diagram.  But the route in question, this one...

"routetoformatterFromLeaf": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint("/modules/formattermodule/inputs/input1")",

is for data that is coming in from external to Edge from 'leaf' or 'downstream' devices, not any modules at all.   does that make sense?

**Comment by sandervandevelde** [comment]
I see. If I call the 'module' "messages" and the output "*" would that make sense? 
Please check your example again.

**Comment by sandervandevelde** [comment]
Please reopen when needed

**Comment by stevebus** [comment]
Doesn't look like I have permissions to re-open (weird)...  my apologies for the slow response, busy week...  I'm not sure that 'module', 'messages', 'output:*' makes sense either, as it's not really a module...  are you familiar with what leaf/downstream devices are?      does the top level UI element have to be a 'module'?   something like "downstream devices" for the name, "messages" for the data, and "output:*" would probably work if that's possible.  Just to indicate that the data is coming from outside if Edge.   It's a pretty common scenario.
